services:
  oidc-radius-bridge:
    build: .
    image: oidc:1.0.2
    container_name: oidc-radius-bridge
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
